---
#--------------------------------------------------------------------------------------------
# Stereo Extrinsic Parameters
#--------------------------------------------------------------------------------------------
body_to_left:
  position:
    x: 0.0 # [m]
    y: 0.0 # [m]
    z: 0.0 # [m]
  orientation:
    w: 1.0
    x: 0.0
    y: 0.0
    z: 0.0
body_to_right:
  position:
    x: 0.05 # [m]
    y: 0.0 # [m]
    z: 0.0 # [m]
  orientation:
    w: 1.0
    x: 0.0
    y: 0.0
    z: 0.0
