---
#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
left:
  image_width: 640
  image_height: 480
  projection:
    fx: 419.617919921875
    fy: 419.617919921875
    cx: 424.94940185546875
    cy: 237.3017578125
  distortion:
    do_undistortion: false
    k1: 0.0
    k2: 0.0
    k3: 0.0
    p1: 0.0
    p2: 0.0
right:
  image_width: 640
  image_height: 480
  projection:
    fx: 419.617919921875
    fy: 419.617919921875
    cx: 424.94940185546875
    cy: 237.3017578125
  distortion:
    do_undistortion: false
    k1: 0.0
    k2: 0.0
    k3: 0.0
    p1: 0.0
    p2: 0.0
